/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author ADMIN
 */
public class DoanhThuPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoanhThuPanel
     */
    public DoanhThuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Ngày", "Doanh thu", "Ghi chú"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 700, 440));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("THỐNG KÊ DOANH THU");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        jLabel1.setText("Ngày:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 100, -1));

        jLabel8.setText("Doanh thu:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, -1, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 90, -1));

        jLabel9.setText("Ghi chú:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 90, -1));

        jButton2.setText("Thêm");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        jLabel7.setText("STT:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel10.setText("Nhập số thứ tự:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 100, -1));

        jButton3.setText("Tìm kiếm");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        jButton4.setText("Sửa");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 830, -1, -1));

        jButton5.setText("Xóa");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 830, -1, -1));

        jButton6.setText("<");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 770, -1, -1));

        jButton7.setText(">");
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 770, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\doan1-nhom2\\src\\img\\Doanhthutest1.jpg")); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
