/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author ADMIN
 */
public class qlyDonHangPanel extends javax.swing.JPanel {

    /**
     * Creates new form qlyDonHang
     */
    public qlyDonHangPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ ĐƠN HÀNG");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 60, -1, -1));

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã đơn hàng", "Tên đơn hàng", "Tên khách đặt", "Ngày đặt"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 329, 711, 343));

        jLabel3.setText("Mã đơn hàng:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 140, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 137, 100, -1));

        jLabel5.setText("Tên đơn hàng:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 174, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 171, 103, -1));

        jLabel6.setText("Tên khách đặt:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 140, -1, -1));

        jLabel7.setText("Ngày đặt:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 174, -1, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 137, 100, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 171, 100, -1));

        jButton1.setText("Thêm");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 220, -1, -1));

        jLabel8.setText("Nhập mã đơn hàng:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 292, -1, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 289, 100, -1));

        jButton2.setText("Tìm kiếm");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 289, -1, -1));

        jButton3.setText("Sửa");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 722, -1, -1));

        jButton4.setText("Xóa");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 722, -1, -1));

        jButton5.setText(">");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 678, -1, -1));

        jButton6.setText("<");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 678, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\doan1-nhom2\\src\\img\\donhangtest3.jpg")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
