/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author ADMIN
 */
public class qlyNhanVienPanel extends javax.swing.JPanel {

    /**
     * Creates new form qlyNhanVienPanel
     */
    public qlyNhanVienPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 52, -1, -1));

        jLabel2.setText("Mã nhân viên :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 137, -1));

        jButton1.setText("Tìm kiếm");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên Nhân Viên", "Chức vụ", "Email", "SĐT", "Lương", "Tài khoản", "Mật Khẩu"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 317, 825, -1));

        jLabel3.setText("Mã NV:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel5.setText("Tên NV:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 70, -1));

        jLabel6.setText("Chức vụ:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 90, -1));

        jLabel7.setText("Email:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, -1, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, -1, -1));

        jLabel8.setText("SĐT:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, -1, -1));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 120, -1, -1));

        jLabel9.setText("Lương:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel10.setText("Tài khoản:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 90, -1));

        jLabel11.setText("Mật khẩu:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, -1, -1));
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 80, -1));

        jButton2.setText("Thêm");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        jButton3.setText("Sửa");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 800, -1, -1));

        jButton4.setText("Làm mới");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 800, -1, -1));

        jButton5.setText("Xóa");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 800, -1, -1));

        jButton6.setText("<");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 750, -1, -1));

        jButton7.setText(">");
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 750, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\doan1-nhom2\\src\\img\\qltruyenthong.jpg")); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1210, -10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
