/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author ADMIN
 */
public class qlyTruyenThongPanel extends javax.swing.JPanel {

    /**
     * Creates new form qlyTruyenThongPanel
     */
    public qlyTruyenThongPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ TRUYỀN THÔNG");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 27, -1, -1));

        jLabel2.setText("Tên chiến dịch");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 101, -1, -1));

        jLabel3.setText("Thời gian:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 135, -1, -1));

        jLabel4.setText("Mục Tiêu:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 197, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 98, 163, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 166, 163, 79));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 132, -1, -1));

        jLabel5.setText("->");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 135, -1, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 132, -1, -1));

        jLabel6.setText("Kênh: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 101, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facebook", "Zalo", "Tiktok", "Twitter", "Khác..." }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 98, 102, -1));

        jLabel7.setText("Ngân sách:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 148, -1, -1));

        jButton1.setText("Thêm");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 98, 80, -1));

        jButton2.setText("Sửa");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 810, -1, -1));

        jButton3.setText("Xóa");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 810, -1, -1));

        jButton4.setText("Tìm kiếm");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 148, -1, -1));

        jTable1.setBackground(new java.awt.Color(243, 250, 255));
        jTable1.setForeground(new java.awt.Color(0, 51, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên Chiến Dịch", "Mục Tiêu", "Thời gian BĐ", "Thời gian KT", "Kênh", "Ngân sách"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 328, 706, -1));

        jLabel10.setText("jLabel10");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 428, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 148, 100, -1));

        jButton5.setText("<");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 760, -1, -1));

        jButton6.setText(">");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 760, -1, -1));

        jButton7.setText("Làm mới");
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 810, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\doan1-nhom2\\src\\img\\background-banner.jpg")); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 0, 1620, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
