/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;

/**
 *
 * @author ADMIN
 */
public class TrangChuqlch extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuqlch
     */
    public TrangChuqlch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btTrangchu = new javax.swing.JButton();
        btDonhang = new javax.swing.JButton();
        btKhachhang = new javax.swing.JButton();
        btKho = new javax.swing.JButton();
        btNhanvien = new javax.swing.JButton();
        btTruyenthong = new javax.swing.JButton();
        btDoanhthu = new javax.swing.JButton();
        btDangxuat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        maincontent = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));

        btTrangchu.setBackground(new java.awt.Color(51, 0, 0));
        btTrangchu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btTrangchu.setForeground(new java.awt.Color(204, 204, 0));
        btTrangchu.setText("Trang Chủ");

        btDonhang.setBackground(new java.awt.Color(51, 0, 0));
        btDonhang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btDonhang.setForeground(new java.awt.Color(204, 204, 0));
        btDonhang.setText("QL Đơn Hàng");
        btDonhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDonhangMouseClicked(evt);
            }
        });

        btKhachhang.setBackground(new java.awt.Color(51, 0, 0));
        btKhachhang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btKhachhang.setForeground(new java.awt.Color(204, 204, 0));
        btKhachhang.setText("QL Khách Hàng");
        btKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btKhachhangMouseClicked(evt);
            }
        });

        btKho.setBackground(new java.awt.Color(51, 0, 0));
        btKho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btKho.setForeground(new java.awt.Color(204, 204, 0));
        btKho.setText("QL Kho Hàng");
        btKho.setToolTipText("");
        btKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btKhoMouseClicked(evt);
            }
        });

        btNhanvien.setBackground(new java.awt.Color(51, 0, 0));
        btNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btNhanvien.setForeground(new java.awt.Color(204, 204, 0));
        btNhanvien.setText("QL Nhân Viên");
        btNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btNhanvienMouseClicked(evt);
            }
        });

        btTruyenthong.setBackground(new java.awt.Color(51, 0, 0));
        btTruyenthong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btTruyenthong.setForeground(new java.awt.Color(204, 204, 0));
        btTruyenthong.setText("QL Truyền Thông");

        btDoanhthu.setBackground(new java.awt.Color(51, 0, 0));
        btDoanhthu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btDoanhthu.setForeground(new java.awt.Color(204, 204, 0));
        btDoanhthu.setText("Doanh Thu");
        btDoanhthu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDoanhthuMouseClicked(evt);
            }
        });

        btDangxuat.setBackground(new java.awt.Color(51, 0, 0));
        btDangxuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btDangxuat.setForeground(new java.awt.Color(204, 204, 0));
        btDangxuat.setText("Đăng Xuất");

        jLabel2.setBackground(new java.awt.Color(153, 153, 0));
        jLabel2.setFont(new java.awt.Font("Serif", 1, 58)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("♕‍  3T CLOTHES ♕");

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("- Nền tảng cho sự thăng hoa -");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btTrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btDonhang, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btKho, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btTruyenthong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btDoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btDangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(374, 374, 374)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(549, 549, 549)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDoanhthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTruyenthong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btKhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDonhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 180));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\doan1-nhom2\\src\\img\\background.png.jpg")); // NOI18N

        javax.swing.GroupLayout maincontentLayout = new javax.swing.GroupLayout(maincontent);
        maincontent.setLayout(maincontentLayout);
        maincontentLayout.setHorizontalGroup(
            maincontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maincontentLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        maincontentLayout.setVerticalGroup(
            maincontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maincontentLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        getContentPane().add(maincontent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1340, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDonhangMouseClicked
        // TODO add your handling code here:
        maincontent.removeAll();
        maincontent.setLayout(new BorderLayout());
        maincontent.add(new qlyDonHangPanel(), BorderLayout.CENTER);
        maincontent.revalidate();
        maincontent.repaint();
    }//GEN-LAST:event_btDonhangMouseClicked

    private void btKhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btKhachhangMouseClicked
        // TODO add your handling code here:
        maincontent.removeAll();
        maincontent.setLayout(new BorderLayout());
        maincontent.add(new qlyKhachHangPanel(), BorderLayout.CENTER);
        maincontent.revalidate();
        maincontent.repaint();
    }//GEN-LAST:event_btKhachhangMouseClicked

    private void btKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btKhoMouseClicked
        // TODO add your handling code here:
        maincontent.removeAll();
        maincontent.setLayout(new BorderLayout());
        maincontent.add(new qlyKhoHangPanel(), BorderLayout.CENTER);
        maincontent.revalidate();
        maincontent.repaint();
    }//GEN-LAST:event_btKhoMouseClicked

    private void btNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNhanvienMouseClicked
        // TODO add your handling code here:
        maincontent.removeAll();
        maincontent.setLayout(new BorderLayout());
        maincontent.add(new qlyNhanVienPanel(), BorderLayout.CENTER);
        maincontent.revalidate();
        maincontent.repaint();
    }//GEN-LAST:event_btNhanvienMouseClicked

    private void btDoanhthuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDoanhthuMouseClicked
        // TODO add your handling code here:
        maincontent.removeAll();
        maincontent.setLayout(new BorderLayout());
        maincontent.add(new DoanhThuPanel(), BorderLayout.CENTER);
        maincontent.revalidate();
        maincontent.repaint();
    }//GEN-LAST:event_btDoanhthuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuqlch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuqlch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuqlch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuqlch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuqlch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangxuat;
    private javax.swing.JButton btDoanhthu;
    private javax.swing.JButton btDonhang;
    private javax.swing.JButton btKhachhang;
    private javax.swing.JButton btKho;
    private javax.swing.JButton btNhanvien;
    private javax.swing.JButton btTrangchu;
    private javax.swing.JButton btTruyenthong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel maincontent;
    // End of variables declaration//GEN-END:variables
}
